export const SCENES = {
  LOAD: 'LOAD_SCENE',
  MENU: 'MENU_SCENE',
  HUD: 'HUD_SCENE',
  GAME: 'GAME_SCENE',
};

export const REGISTRY_KEYS = {
  SCORE: 'SCORE',
  LIVES: 'LIVES'
};

export const TEXT_ELEMENTS_KEYS = REGISTRY_KEYS;

export const EVENTS = {
  SCORE_CHANGED: 'SCORE_CHANGED',
  DECREASE_LIVES: 'DESCREASE_LIVES'
};

export const INPUTS = {
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  JUMP: 'UP',
  DOWN: 'DOWN'
};

export const PLAYER_ANIMATIONS = {
  IDLE: 'PLAYER_IDLE',
  RUN: 'PLAYER_RUN',
  JUMP: 'PLAYER_JUMP',
  LAND: 'PLAYER_LAND',
  DAMAGE: 'PLAYER_DAMAGE'
};

export const ENEMY_ANIMATIONS = {
  RUN: 'ENEMY_RUN'
};
