export const SCENES = {
  LOAD: 'LOAD_SCENE',
  MENU: 'MENU_SCENE',
  HUD: 'HUD_SCENE',
  GAME: 'GAME_SCENE',
};

export const REGISTRY_KEYS = {
  SCORE: 'SCORE'
};

export const PLAYER_ANIMATIONS = {
  IDLE: 'PLAYER_IDLE',
  RUN: 'PLAYER_RUN',
  JUMP: 'PLAYER_JUMP',
  LAND: 'PLAYER_LAND',
  DAMAGE: 'PLAYER_DAMAGE'
};
